[package]
name = "rustic"
version = "0.1.0"
authors = ["Pema Malling <pemamalling@gmail.com>"]
edition = "2021"

[dependencies]
shared_structs = { path = "shared_structs" }
bytemuck = { version = "1.13.1", features = ["derive"] }
glam = { version = "0.22.0", features = ["bytemuck"] }
gpgpu = { version = "0.2.0", features = ["image", "integrate-image"] }
image = "0.24.6"
rand = "0.8.5"
oidn = { version = "1.4.3", optional = true }
imgui = "0.11.0"
glium = "0.32.1"
imgui-glium-renderer = "0.11.0"
imgui-winit-support = "0.11.0"
lazy_static = "1.4.0"

[build-dependencies]
spirv-builder = "0.7.0"

[features]
oidn = ["dep:oidn"]

[profile.dev.package."*"]
opt-level = 3
